#!/usr/bin/env bash
# =============================================================================
# new-project.sh — Bootstrap a new project with a chosen dev stack
# =============================================================================
# Usage:
#   ./scripts/new-project.sh <project-name> <stack>
#
# Stacks:
#   web-api        — Postgres + Redis + MailHog
#   microservices  — Postgres + Kafka + Jaeger + Prometheus + Grafana
#   devops         — Gitea + Jenkins + SonarQube + Portainer
#   cloud-local    — LocalStack + MinIO
#   data-ml        — Jupyter + Postgres + MinIO
#
# Runtime flags (optional, can combine):
#   --node     — add Node.js 
#   --python   — add Python
#   --rust     — add Rust
#   --go       — add Go
#   --java     — add Java
#
# Examples:
#   ./scripts/new-project.sh my-api web-api --node
#   ./scripts/new-project.sh ml-project data-ml --python
#   ./scripts/new-project.sh backend web-api --rust
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()     { echo -e "${CYAN}${BOLD}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}${BOLD}[OK]${RESET}    $*"; }
error()   { echo -e "${RED}${BOLD}[ERROR]${RESET} $*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Args ──────────────────────────────────────────────────────────────────────
[[ $# -lt 2 ]] && error "Usage: $0 <project-name> <stack> [--node] [--python] [--rust] [--go] [--java]"

PROJECT_NAME="$1"
STACK="$2"
shift 2

ADD_NODE=false
ADD_PYTHON=false
ADD_RUST=false
ADD_GO=false
ADD_JAVA=false

for arg in "$@"; do
  case "$arg" in
    --node)   ADD_NODE=true ;;
    --python) ADD_PYTHON=true ;;
    --rust)   ADD_RUST=true ;;
    --go)     ADD_GO=true ;;
    --java)   ADD_JAVA=true ;;
    *) error "Unknown flag: $arg" ;;
  esac
done

PROJECT_DIR="$(pwd)/$PROJECT_NAME"

# ── Validate ──────────────────────────────────────────────────────────────────
VALID_STACKS=("web-api" "microservices" "devops" "cloud-local" "data-ml")
STACK_VALID=false
for s in "${VALID_STACKS[@]}"; do
  [[ "$s" == "$STACK" ]] && STACK_VALID=true
done
[[ "$STACK_VALID" == false ]] && error "Unknown stack: $STACK. Valid: ${VALID_STACKS[*]}"
[[ -d "$PROJECT_DIR" ]] && error "Directory already exists: $PROJECT_DIR"

# ── Create project ────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║     Podman Dev Stacks — Project Bootstrap    ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""
log "Project : ${BOLD}$PROJECT_NAME${RESET}"
log "Stack   : ${BOLD}$STACK${RESET}"
log "Path    : ${BOLD}$PROJECT_DIR${RESET}"
echo ""

mkdir -p "$PROJECT_DIR"

# Copy base stack compose file
cp "$REPO_ROOT/stacks/$STACK/compose.yml" "$PROJECT_DIR/compose.yml"

# Copy extra files if they exist (e.g. prometheus.yml)
for extra in "$REPO_ROOT/stacks/$STACK/"*; do
  fname="$(basename "$extra")"
  [[ "$fname" == "compose.yml" ]] && continue
  cp "$extra" "$PROJECT_DIR/$fname"
  log "Copied extra config: $fname"
done

# ── Merge runtime into compose.yml ────────────────────────────────────────────
append_runtime() {
  local runtime="$1"
  local src="$REPO_ROOT/runtimes/$runtime/compose-service.yml"
  if [[ -f "$src" ]]; then
    echo "" >> "$PROJECT_DIR/compose.yml"
    echo "  # ── $runtime runtime ──────────────────────────────" >> "$PROJECT_DIR/compose.yml"
    cat "$src" >> "$PROJECT_DIR/compose.yml"
    success "Added $runtime runtime to compose.yml"
  fi

  # Copy Dockerfile if present
  local dockerfile="$REPO_ROOT/runtimes/$runtime/Dockerfile"
  if [[ -f "$dockerfile" ]]; then
    cp "$dockerfile" "$PROJECT_DIR/Dockerfile.$runtime"
    log "Copied Dockerfile.$runtime"
  fi
}

[[ "$ADD_NODE"   == true ]] && append_runtime "node"
[[ "$ADD_PYTHON" == true ]] && append_runtime "python"
[[ "$ADD_RUST"   == true ]] && append_runtime "rust"
[[ "$ADD_GO"     == true ]] && append_runtime "go"
[[ "$ADD_JAVA"   == true ]] && append_runtime "java"

# ── Create .env ───────────────────────────────────────────────────────────────
cat > "$PROJECT_DIR/.env" <<EOF
# Environment variables for $PROJECT_NAME
# Generated by new-project.sh on $(date +%Y-%m-%d)

# Postgres
POSTGRES_USER=dev
POSTGRES_PASSWORD=devpass
POSTGRES_DB=${PROJECT_NAME//-/_}

# Redis
REDIS_PORT=6379

# App
APP_PORT=3000
NODE_ENV=development
PYTHONUNBUFFERED=1
RUST_LOG=debug
EOF

# ── Create .gitignore ─────────────────────────────────────────────────────────
cat > "$PROJECT_DIR/.gitignore" <<EOF
# Dependencies
node_modules/
target/
__pycache__/
*.pyc
.venv/
vendor/

# Build outputs
dist/
build/
*.o
*.a

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/
EOF

# ── Print next steps ──────────────────────────────────────────────────────────
echo ""
success "Project '${PROJECT_NAME}' created at ${PROJECT_DIR}"
echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo ""
echo -e "  ${CYAN}cd $PROJECT_NAME${RESET}"
echo -e "  ${CYAN}podman compose up -d${RESET}          # start all services"
echo -e "  ${CYAN}podman compose ps${RESET}             # check status"
echo -e "  ${CYAN}podman compose logs -f${RESET}        # follow logs"
echo -e "  ${CYAN}podman compose down${RESET}           # stop (data preserved)"
echo -e "  ${CYAN}podman compose down -v${RESET}        # stop + wipe volumes"
echo ""
